<?php
/**
 * Created by PhpStorm.
 * User: odeen
 * Date: 2017/8/4
 * Time: 下午6:07
 */
namespace App\Repositories;


use App\Models\Admin;


class AdminRepository extends BaseRepository
{

    public function __construct(Admin $customer)
    {
        $this->model = $customer;
    }

    public function create(array $data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    /**
     * 更新用户
     * @param array $data
     * @return mixed
     */
    public function update(array $data)
    {
        $admin = $this->findBy('name',$data['name']);
        if($admin instanceof Admin){
            return $admin->update($data);
        }else{
            return false;
        }
    }

    /**
     * 获取用户列表
     * @param $page
     * @return \Illuminate\Contracts\Pagination\LengthAwarePaginator
     */
    public function getList($page)
    {
        $query = $this->model->newQuery();
        $paginate = $query->paginate(10,['id','name','level'],'page',$page);
        return $paginate;
    }


}